<?
$aMenuLinks = Array(
	/*Array(
		"АКЦИЯ!", 
		"/katalog/prazdniki/den-rozhdeniya-banka/", 
		Array(), 
		Array(), 
		"" 
	),*/
	Array(
		"Новинки", 
		"/katalog/novinki/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Скидки", 
		"/katalog/1skidki/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Золото", 
		"/katalog/zoloto/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Слитки", 
		"/katalog/slitki/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Иностранные", 
		"/katalog/inostrannye/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Российские", 
		"/katalog/rossiyskie/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Инвестиционные", 
		"/katalog/?set_filter=y&arrFilter_50_1886922373=Y&arrFilter_57_1547219295=Y", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Юбилейные", 
		"/katalog/yubileynye-i-pamyatnye-monety/", 
		Array(), 
		Array(), 
		"" 
	),
    Array(
        "Памятные монеты",
        "/katalog/?set_filter=y&arrFilter_54_2316230027=Y&arrFilter_50_219956312=Y&arrFilter_50_1886922373=Y&arrFilter_50_2644728265=Y",
        Array(),
        Array(),
        ""
    ),
);
?>